version: '3.8'

services:
 app:
  image: owftecnologia/demo-back-end-gemini:1.1
  restart: always
  container_name: demo-back-end-gemini
  ports:
   - '3000:3000'
  volumes:
   - .:/usr/src/app
   - /usr/src/app/node_modules
  environment:
   - NODE_ENV=development
  command: npm run prod
